import json
import subprocess
import os
import sys
from datetime import datetime

TARGETS = [
    {
        "name": "freeCodeCamp",
        "repo": "freeCodeCamp/freeCodeCamp",
        "label": "help wanted",
        "icon": "🏕️",
        "description": "Global developer reciprocity & curriculum tasks (open to all, no permission needed)"
    },
    {
        "name": "NOAA weather.gov 2.0",
        "repo": "weather-gov/weather.gov",
        "label": "help wanted",
        "icon": "🌤️",
        "description": "Federal atmospheric telemetry & USWDS web modernization"
    },
    {
        "name": "NIST Dioptra",
        "repo": "usnistgov/dioptra",
        "label": "help wanted",
        "icon": "🌐",
        "description": "Federal AI Risk Management Framework (AI RMF 1.0) & security evaluation"
    },
    {
        "name": "WHIPS Satellite Gridding",
        "repo": "barronh/WHIPS",
        "label": None,
        "icon": "🛰️",
        "description": "UW-Madison SAGE / Dr. Tracey Holloway Group satellite gridding"
    },
    {
        "name": "The Agent Hinge (Cre8)",
        "repo": "tmorrowdev/cre8-gemini-extension",
        "label": None,
        "icon": "💍",
        "description": "Tyler Morrow's Gemini CLI extension + FastMCP UI"
    }
]

def fetch_issues(repo, label=None, limit=5):
    cmd = f'gh issue list --repo {repo} --state open --limit {limit} --json number,title,labels,url,createdAt'
    if label:
        cmd += f' --label "{label}"'
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if res.returncode != 0:
        # Fallback without label
        cmd_fallback = f'gh issue list --repo {repo} --state open --limit {limit} --json number,title,labels,url,createdAt'
        res_fb = subprocess.run(cmd_fallback, shell=True, capture_output=True, text=True)
        if res_fb.returncode == 0 and res_fb.stdout.strip():
            try:
                return json.loads(res_fb.stdout)
            except:
                return []
        return []
    try:
        return json.loads(res.stdout)
    except:
        return []

def generate_digest():
    now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# 🏕️ Campsite Radar: Live Issue & Bug Crawler",
        f"**Last Automated Crawl**: `{now_str}`",
        "",
        "> *\"Leave the campsite cleaner than you found it. Here are the freshest upstream issues ready for intellectual bread.\"*",
        "",
        "---",
        ""
    ]

    total_issues = 0
    all_found = []

    for target in TARGETS:
        repo = target["repo"]
        name = target["name"]
        icon = target["icon"]
        desc = target["description"]
        label = target["label"]

        print(f"Crawling {repo}...")
        issues = fetch_issues(repo, label, limit=4)
        lines.append(f"### {icon} {name} ([`{repo}`](https://github.com/{repo}))")
        lines.append(f"_{desc}_\n")

        if not issues:
            lines.append("`No active issues matching filter right now. Radar standing by.`\n")
        else:
            total_issues += len(issues)
            for iss in issues:
                num = iss.get("number")
                title = iss.get("title", "Untitled")
                url = iss.get("url")
                created = iss.get("createdAt", "")[:10]
                label_names = [l.get("name") for l in iss.get("labels", []) if isinstance(l, dict)]
                labels_str = " ".join([f"`{l}`" for l in label_names[:3]])
                
                entry = f"* [**#{num}: {title}**]({url}) ({created}) {labels_str}"
                lines.append(entry)
                all_found.append({
                    "repo": repo,
                    "num": num,
                    "title": title,
                    "url": url
                })
            lines.append("")

    lines.append("---")
    lines.append("<sub>Generated by TrendingTea Campsite CI/CD Crawler · Automated Upstream Reciprocity</sub>\n")
    
    digest_text = "\n".join(lines)
    return digest_text, total_issues, all_found

if __name__ == "__main__":
    digest, count, items = generate_digest()
    
    # Write CAMPSITE_RADAR.md
    out_path = "CAMPSITE_RADAR.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(digest)
    print(f"Wrote {out_path} with {count} active issues across target repositories!")
